import {esc,money} from './core.js';
import {budgetSuggestions} from './spending.js';
const colors=['#17675f','#507fd0','#d39031','#9270b3','#bd5970','#7e9635','#398d9d','#80543c','#64748b','#b04fba','#357b4c','#ae6d31'];
export function spendingChart(snapshot,scope){
  const categories=snapshot.categories.filter(c=>c.actual_cents>0).sort((a,b)=>b.actual_cents-a.actual_cents),total=categories.reduce((s,c)=>s+c.actual_cents,0);
  let angle=-Math.PI/2;
  const slices=categories.map((c,i)=>{
    const fraction=c.actual_cents/total,next=angle+fraction*Math.PI*2,x=110+100*Math.cos(angle),y=110+100*Math.sin(angle),endX=110+100*Math.cos(next),endY=110+100*Math.sin(next);
    const shape=fraction===1?'<circle cx="110" cy="110" r="100"':`<path d="M110 110 L${x} ${y} A100 100 0 ${fraction>.5?1:0} 1 ${endX} ${endY} Z"`;
    angle=next;return `${shape} fill="${colors[i%colors.length]}" stroke="white" stroke-width="2"><title>${esc(c.name)}: ${money(c.actual_cents)} (${(fraction*100).toFixed(1)}%)</title></${fraction===1?'circle':'path'}>`;
  }).join('');
  return `<section class="panel spending-panel"><div class="row between"><div><span class="eyebrow">Where your money went</span><h2>Spending by category</h2><p class="muted">${esc(scope)} · ${esc(snapshot.month)}</p></div><div class="chart-total"><small>Net spending</small><strong>${money(snapshot.spending_cents)}</strong></div></div>${total?`<div class="spending-layout"><svg class="spending-pie" viewBox="0 0 220 220" role="img" aria-label="Spending by category; amounts and percentages are listed alongside">${slices}</svg><div class="spending-legend">${categories.map((c,i)=>`<button class="legend-row" data-view-filter="" data-view-category="${esc(c.id)}"><svg width="14" height="14" viewBox="0 0 14 14" aria-hidden="true"><circle cx="7" cy="7" r="7" fill="${colors[i%colors.length]}"/></svg><span>${esc(c.name)}</span><b>${money(c.actual_cents)}</b><small>${(c.actual_cents/total*100).toFixed(1)}%</small></button>`).join('')}</div></div>`:'<p class="empty">No categorized spending for this selection. Choose another account or month, or review your transactions.</p>'}<p class="footnote">Refunds reduce their category’s spending. Categories with net credits are omitted from the pie. Transfers, savings, pending items and excluded duplicates are omitted. ${money(snapshot.unresolved_outgoing_cents)} in unresolved outgoing payments is not yet included.</p></section>`;
}
export function budgetRecommendationCards(snapshot,scope,individual=false){
  const suggestions=budgetSuggestions(snapshot);
  return `<section class="budget-recommendations"><div class="section-head"><div><span class="eyebrow">Based on current spending</span><h2>Budget adjustments to consider</h2><small>${esc(scope)} · Updates when your transactions change</small></div></div>${suggestions.length?`<div class="focus-list">${suggestions.map(c=>`<article class="insight"><span class="eyebrow">${c.target_cents?'Review target':'Set a target'}</span><h3>${esc(c.name)}</h3><p>${money(c.actual_cents)} spent · ${money(c.target_cents)} budgeted${c.projected_cents!=null?`<br>${money(c.projected_cents)} estimated at month end`:''}</p><p><b>Consider ${money(c.proposed_target_cents)}</b> ${snapshot.period==='past'?'as a starting point for next month':'for this month'}.</p><small>${individual?'This account is only part of your household budget. ':''}${c.projected_cents!=null?'Estimate assumes recorded spending continues at the same daily pace. ':'Based on recorded spending so far. '}Confirm imports and offset any increase with a cut elsewhere or confirmed income.</small><div class="row section-head"><button data-budget-suggestion="${esc(c.id)}">Review budget change</button><button class="quiet" data-view-filter="" data-view-category="${esc(c.id)}">View spending</button></div></article>`).join('')}</div>`:'<div class="notice">No higher targets suggested from the recorded spending. Keep reviewing upcoming bills and unclassified transactions before reducing a budget.</div>'}<p class="footnote">These automatic calculations are separate from the optional AI review below. Suggestions never change a budget until you save. Missing imports can change the result.</p></section>`;
}
